export const countryCodeToName = {
  IND: "india",
  USA: "united states",
  US: "united states",
  GBR: "united kingdom",
  GB: "united kingdom",
  UK: "united kingdom",
  CAN: "canada",
  CA: "canada",
  AUS: "australia",
  AU: "australia",
  DEU: "germany",
  DE: "germany",
  FRA: "france",
  FR: "france",
  ESP: "spain",
  ES: "spain",
  ITA: "italy",
  IT: "italy",
  BRA: "brazil",
  BR: "brazil",
  MEX: "mexico",
  MX: "mexico",
  RUS: "russia",
  RU: "russia",
  CHN: "china",
  CN: "china",
  JPN: "japan",
  JP: "japan",
  KOR: "south korea",
  KR: "south korea",
  AW: "aruba",
  ABW: "aruba",
  AF: "afghanistan",
  AFG: "afghanistan",
  AO: "angola",
  AGO: "angola",
  AI: "anguilla",
  AIA: "anguilla",
  AX: "Åland islands",
  ALA: "Åland islands",
  AL: "albania",
  ALB: "albania",
  AD: "andorra",
  AND: "andorra",
  AE: "united arab emirates",
  ARE: "united arab emirates",
  AR: "argentina",
  ARG: "argentina",
  AM: "armenia",
  ARM: "armenia",
  AS: "american samoa",
  ASM: "american samoa",
  AQ: "antarctica",
  ATA: "antarctica",
  TF: "french southern territories",
  ATF: "french southern territories",
  AG: "antigua and barbuda",
  ATG: "antigua and barbuda",
  AT: "austria",
  AUT: "austria",
  AZ: "azerbaijan",
  AZE: "azerbaijan",
  BI: "burundi",
  BDI: "burundi",
  BE: "belgium",
  BEL: "belgium",
  BJ: "benin",
  BEN: "benin",
  BQ: "bonaire, sint eustatius and saba",
  BES: "bonaire, sint eustatius and saba",
  BF: "burkina faso",
  BFA: "burkina faso",
  BD: "bangladesh",
  BGD: "bangladesh",
  BG: "bulgaria",
  BGR: "bulgaria",
  BH: "bahrain",
  BHR: "bahrain",
  BS: "bahamas",
  BHS: "bahamas",
  BA: "bosnia and herzegovina",
  BIH: "bosnia and herzegovina",
  BL: "saint barthélemy",
  BLM: "saint barthélemy",
  BY: "belarus",
  BLR: "belarus",
  BZ: "belize",
  BLZ: "belize",
  BM: "bermuda",
  BMU: "bermuda",
  BO: "bolivia, plurinational state of",
  BOL: "bolivia, plurinational state of",
  BB: "barbados",
  BRB: "barbados",
  BN: "brunei darussalam",
  BRN: "brunei darussalam",
  BT: "bhutan",
  BTN: "bhutan",
  BV: "bouvet island",
  BVT: "bouvet island",
  BW: "botswana",
  BWA: "botswana",
  CF: "central african republic",
  CAF: "central african republic",
  CC: "cocos (keeling) islands",
  CCK: "cocos (keeling) islands",
  CH: "switzerland",
  CHE: "switzerland",
  CL: "chile",
  CHL: "chile",
  CI: "côte d'ivoire",
  CIV: "côte d'ivoire",
  CM: "cameroon",
  CMR: "cameroon",
  CD: "congo, the democratic republic of the",
  COD: "congo, the democratic republic of the",
  CG: "congo",
  COG: "congo",
  CK: "cook islands",
  COK: "cook islands",
  CO: "colombia",
  COL: "colombia",
  KM: "comoros",
  COM: "comoros",
  CV: "cabo verde",
  CPV: "cabo verde",
  CR: "costa rica",
  CRI: "costa rica",
  CU: "cuba",
  CUB: "cuba",
  CW: "cura\u00e7ao",
  CUW: "cura\u00e7ao",
  CX: "christmas island",
  CXR: "christmas island",
  KY: "cayman islands",
  CYM: "cayman islands",
  CY: "cyprus",
  CYP: "cyprus",
  CZ: "czechia",
  CZE: "czechia",
  DJ: "djibouti",
  DJI: "djibouti",
  DM: "dominica",
  DMA: "dominica",
  DK: "denmark",
  DNK: "denmark",
  DO: "dominican republic",
  DOM: "dominican republic",
  DZ: "algeria",
  DZA: "algeria",
  EC: "ecuador",
  ECU: "ecuador",
  EG: "egypt",
  EGY: "egypt",
  ER: "eritrea",
  ERI: "eritrea",
  EH: "western sahara",
  ESH: "western sahara",
  EE: "estonia",
  EST: "estonia",
  ET: "ethiopia",
  ETH: "ethiopia",
  FI: "finland",
  FIN: "finland",
  FJ: "fiji",
  FJI: "fiji",
  FK: "falkland islands (malvinas)",
  FLK: "falkland islands (malvinas)",
  FO: "faroe islands",
  FRO: "faroe islands",
  FM: "micronesia, federated states of",
  FSM: "micronesia, federated states of",
  GA: "gabon",
  GAB: "gabon",
  GE: "georgia",
  GEO: "georgia",
  GG: "guernsey",
  GGY: "guernsey",
  GH: "ghana",
  GHA: "ghana",
  GI: "gibraltar",
  GIB: "gibraltar",
  GN: "guinea",
  GIN: "guinea",
  GP: "guadeloupe",
  GLP: "guadeloupe",
  GM: "gambia",
  GMB: "gambia",
  GW: "guinea-bissau",
  GNB: "guinea-bissau",
  GQ: "equatorial guinea",
  GNQ: "equatorial guinea",
  GR: "greece",
  GRC: "greece",
  GD: "grenada",
  GRD: "grenada",
  GL: "greenland",
  GRL: "greenland",
  GT: "guatemala",
  GTM: "guatemala",
  GF: "french guiana",
  GUF: "french guiana",
  GU: "guam",
  GUM: "guam",
  GY: "guyana",
  GUY: "guyana",
  HK: "hong kong",
  HKG: "hong kong",
  HM: "heard island and mcdonald islands",
  HMD: "heard island and mcdonald islands",
  HN: "honduras",
  HND: "honduras",
  HR: "croatia",
  HRV: "croatia",
  HT: "haiti",
  HTI: "haiti",
  HU: "hungary",
  HUN: "hungary",
  ID: "indonesia",
  IDN: "indonesia",
  IM: "isle of man",
  IMN: "isle of man",
  IN: "india",
  IO: "british indian ocean territory",
  IOT: "british indian ocean territory",
  IE: "ireland",
  IRL: "ireland",
  IR: "iran, islamic republic of",
  IRN: "iran, islamic republic of",
  IQ: "iraq",
  IRQ: "iraq",
  IS: "iceland",
  ISL: "iceland",
  IL: "israel",
  ISR: "israel",
  JM: "jamaica",
  JAM: "jamaica",
  JE: "jersey",
  JEY: "jersey",
  JO: "jordan",
  JOR: "jordan",
  KZ: "kazakhstan",
  KAZ: "kazakhstan",
  KE: "kenya",
  KEN: "kenya",
  KG: "kyrgyzstan",
  KGZ: "kyrgyzstan",
  KH: "cambodia",
  KHM: "cambodia",
  KI: "kiribati",
  KIR: "kiribati",
  KN: "saint kitts and nevis",
  KNA: "saint kitts and nevis",
  KW: "kuwait",
  KWT: "kuwait",
  LA: "lao people's democratic republic",
  LAO: "lao people's democratic republic",
  LB: "lebanon",
  LBN: "lebanon",
  LR: "liberia",
  LBR: "liberia",
  LY: "libya",
  LBY: "libya",
  LC: "saint lucia",
  LCA: "saint lucia",
  LI: "liechtenstein",
  LIE: "liechtenstein",
  LK: "sri lanka",
  LKA: "sri lanka",
  LS: "lesotho",
  LSO: "lesotho",
  LT: "lithuania",
  LTU: "lithuania",
  LU: "luxembourg",
  LUX: "luxembourg",
  LV: "latvia",
  LVA: "latvia",
  MO: "macao",
  MAC: "macao",
  MF: "saint martin (french part)",
  MAF: "saint martin (french part)",
  MA: "morocco",
  MAR: "morocco",
  MC: "monaco",
  MCO: "monaco",
  MD: "moldova, republic of",
  MDA: "moldova, republic of",
  MG: "madagascar",
  MDG: "madagascar",
  MV: "maldives",
  MDV: "maldives",
  MH: "marshall islands",
  MHL: "marshall islands",
  MK: "north macedonia",
  MKD: "north macedonia",
  ML: "mali",
  MLI: "mali",
  MT: "malta",
  MLT: "malta",
  MM: "myanmar",
  MMR: "myanmar",
  ME: "montenegro",
  MNE: "montenegro",
  MN: "mongolia",
  MNG: "mongolia",
  MP: "northern mariana islands",
  MNP: "northern mariana islands",
  MZ: "mozambique",
  MOZ: "mozambique",
  MR: "mauritania",
  MRT: "mauritania",
  MS: "montserrat",
  MSR: "montserrat",
  MQ: "martinique",
  MTQ: "martinique",
  MU: "mauritius",
  MUS: "mauritius",
  MW: "malawi",
  MWI: "malawi",
  MY: "malaysia",
  MYS: "malaysia",
  YT: "mayotte",
  MYT: "mayotte",
  NA: "namibia",
  NAM: "namibia",
  NC: "new caledonia",
  NCL: "new caledonia",
  NE: "niger",
  NER: "niger",
  NF: "norfolk island",
  NFK: "norfolk island",
  NG: "nigeria",
  NGA: "nigeria",
  NI: "nicaragua",
  NIC: "nicaragua",
  NU: "niue",
  NIU: "niue",
  NL: "netherlands",
  NLD: "netherlands",
  NO: "norway",
  NOR: "norway",
  NP: "nepal",
  NPL: "nepal",
  NR: "nauru",
  NRU: "nauru",
  NZ: "new zealand",
  NZL: "new zealand",
  OM: "oman",
  OMN: "oman",
  PK: "pakistan",
  PAK: "pakistan",
  PA: "panama",
  PAN: "panama",
  PN: "pitcairn",
  PCN: "pitcairn",
  PE: "peru",
  PER: "peru",
  PH: "philippines",
  PHL: "philippines",
  PW: "palau",
  PLW: "palau",
  PG: "papua new guinea",
  PNG: "papua new guinea",
  PL: "poland",
  POL: "poland",
  PR: "puerto rico",
  PRI: "puerto rico",
  KP: "korea, democratic people's republic of",
  PRK: "korea, democratic people's republic of",
  PT: "portugal",
  PRT: "portugal",
  PY: "paraguay",
  PRY: "paraguay",
  PS: "palestine, state of",
  PSE: "palestine, state of",
  PF: "french polynesia",
  PYF: "french polynesia",
  QA: "qatar",
  QAT: "qatar",
  RE: "r\u00e9union",
  REU: "r\u00e9union",
  RO: "romania",
  ROU: "romania",
  RW: "rwanda",
  RWA: "rwanda",
  SA: "saudi arabia",
  SAU: "saudi arabia",
  SD: "sudan",
  SDN: "sudan",
  SN: "senegal",
  SEN: "senegal",
  SG: "singapore",
  SGP: "singapore",
  GS: "south georgia and the south sandwich islands",
  SGS: "south georgia and the south sandwich islands",
  SH: "saint helena, ascension and tristan da cunha",
  SHN: "saint helena, ascension and tristan da cunha",
  SJ: "svalbard and jan mayen",
  SJM: "svalbard and jan mayen",
  SB: "solomon islands",
  SLB: "solomon islands",
  SL: "sierra leone",
  SLE: "sierra leone",
  SV: "el salvador",
  SLV: "el salvador",
  SM: "san marino",
  SMR: "san marino",
  SO: "somalia",
  SOM: "somalia",
  PM: "saint pierre and miquelon",
  SPM: "saint pierre and miquelon",
  RS: "serbia",
  SRB: "serbia",
  SS: "south sudan",
  SSD: "south sudan",
  ST: "sao tome and principe",
  STP: "sao tome and principe",
  SR: "suriname",
  SUR: "suriname",
  SK: "slovakia",
  SVK: "slovakia",
  SI: "slovenia",
  SVN: "slovenia",
  SE: "sweden",
  SWE: "sweden",
  SZ: "eswatini",
  SWZ: "eswatini",
  SX: "sint maarten (dutch part)",
  SXM: "sint maarten (dutch part)",
  SC: "seychelles",
  SYC: "seychelles",
  SY: "syrian arab republic",
  SYR: "syrian arab republic",
  TC: "turks and caicos islands",
  TCA: "turks and caicos islands",
  TD: "chad",
  TCD: "chad",
  TG: "togo",
  TGO: "togo",
  TH: "thailand",
  THA: "thailand",
  TJ: "tajikistan",
  TJK: "tajikistan",
  TK: "tokelau",
  TKL: "tokelau",
  TM: "turkmenistan",
  TKM: "turkmenistan",
  TL: "timor-leste",
  TLS: "timor-leste",
  TO: "tonga",
  TON: "tonga",
  TT: "trinidad and tobago",
  TTO: "trinidad and tobago",
  TN: "tunisia",
  TUN: "tunisia",
  TR: "turkey",
  TUR: "turkey",
  TV: "tuvalu",
  TUV: "tuvalu",
  TW: "taiwan, province of china",
  TWN: "taiwan, province of china",
  TZ: "tanzania, united republic of",
  TZA: "tanzania, united republic of",
  UG: "uganda",
  UGA: "uganda",
  UA: "ukraine",
  UKR: "ukraine",
  UM: "united states minor outlying islands",
  UMI: "united states minor outlying islands",
  UY: "uruguay",
  URY: "uruguay",
  UZ: "uzbekistan",
  UZB: "uzbekistan",
  VA: "holy see (vatican city state)",
  VAT: "holy see (vatican city state)",
  VC: "saint vincent and the grenadines",
  VCT: "saint vincent and the grenadines",
  VE: "venezuela, bolivarian republic of",
  VEN: "venezuela, bolivarian republic of",
  VG: "virgin islands, british",
  VGB: "virgin islands, british",
  VI: "virgin islands, u.s.",
  VIR: "virgin islands, u.s.",
  VN: "viet nam",
  VNM: "viet nam",
  VU: "vanuatu",
  VUT: "vanuatu",
  WF: "wallis and futuna",
  WLF: "wallis and futuna",
  WS: "samoa",
  WSM: "samoa",
  YE: "yemen",
  YEM: "yemen",
  ZA: "south africa",
  ZAF: "south africa",
  ZM: "zambia",
  ZMB: "zambia",
  ZW: "zimbabwe",
  ZWE: "zimbabwe",
};
